[workspace]
members = [
    "apis/lora",
    "drivers/lora/sx127x",
    "device",
    "kernel",
    "macros",
    "xtask",
]

[patch.crates-io]
cortex-m = {git = "https://github.com/rust-embedded/cortex-m.git", branch = "master", features = ["device"]}
