[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
name = "drogue-device-rak811"
version = "0.1.0"
edition = "2018"
description = "Async driver for RAK811 LoRa AT command firmware"
