[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-uart"
version = "0.1.0"

[workspace]

[dependencies.defmt]
version = "0.2"

[dependencies.defmt-rtt]
version = "0.2"

[dependencies.drogue-device-kernel]
path = "../../../kernel"
features = ["defmt", "defmt-trace" ]

[dependencies.embassy]
git = "https://github.com/embassy-rs/embassy.git"
features = ["defmt", "defmt-info" ]

[dependencies.embassy-nrf]
git = "https://github.com/embassy-rs/embassy.git"
features = ["defmt", "defmt-info", "52833" ]

[dependencies.embassy-traits]
git = "https://github.com/embassy-rs/embassy.git"

[dependencies.cortex-m-rt]
version = "0.6"

[dependencies.cortex-m]
version = "0.7"
features = ["inline-asm"]

[dependencies.panic-probe]
version = "0.2.0"
features = ["print-defmt"]

[dependencies.futures]
version = "0.3.8"
default-features = false
features = ["async-await"]

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
