[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-device"
version = "0.1.0"

[lib]
doctest = false

[dependencies.drogue-device-kernel]
path = "../kernel"

[dependencies.drogue-device-macros]
path = "../macros"

[dependencies.embassy]
# git = "https://github.com/embassy-rs/embassy.git"
git = "https://github.com/lulf/embassy.git"
branch = "reexport-macro-param"
default-features = false

[dependencies.embassy-nrf]
# git = "https://github.com/embassy-rs/embassy.git"
git = "https://github.com/lulf/embassy.git"
branch = "reexport-macro-param"
default-features = false
optional = true

[dependencies.embassy-std]
# git = "https://github.com/embassy-rs/embassy.git"
git = "https://github.com/lulf/embassy.git"
branch = "reexport-macro-param"
default-features = false
optional = true

[dev-dependencies.embassy-std]
# git = "https://github.com/embassy-rs/embassy.git"
git = "https://github.com/lulf/embassy.git"
branch = "reexport-macro-param"
default-features = false

[dependencies.log]
version = "0.4"
optional = true

[dependencies.defmt]
version = "0.2"
optional = true

[features]
"chip+nrf52833" = ["embassy-nrf", "embassy-nrf/52833"]
std = ["embassy/std", "embassy-std"]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
