[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-device-example-std-hello"
version = "0.1.0"

[workspace]

[dependencies.log]
version = "0.4"

[dependencies.env_logger]
version = "0.8"

[dependencies.drogue-device-kernel]
path = "../../../kernel"
features = ["log", "std"]

[dependencies.embassy]
git = "https://github.com/embassy-rs/embassy.git"
features = [ "log", "std" ]

[dependencies.embassy-std]
git = "https://github.com/embassy-rs/embassy.git"

[patch.crates-io]
cortex-m = {git = "https://github.com/rust-embedded/cortex-m.git", branch = "master", features = ["device"]}
